"""The little genomes the tutorials install.

Teaching someone the download view is awkward: a real assembly is gigabytes and needs a
network. So the tutorials ship their own, and there are two of them, because they teach
different things.

*Ensemblus welcomus* — twenty-two kilobases of invented sequence across two contigs, with
genes called Welcome, To, Ensembl and Go — is for **Getting Started**, where the point is
the shape of the workflow and the genome is only something to carry through it.

The **GRCh38 REG4 slice** is for the browser tutorial, where the genome *is* the subject:
half a megabase of real chromosome 1 with its real Ensembl annotation, so there are genes
with thirty-eight transcripts to flatten, four gene classes to filter, and sequence worth
zooming into. Its coordinates are the true ones — the FASTA record is chromosome ``1``
with ``N`` in front of the window — so REG4 answers at 1:119,794,017 here exactly as it
does on the Ensembl website.

Installing either means copying its files into the same ``local_data`` layout a download
produces, under the same naming rules, with the same manifest. Nothing downstream knows
or cares that they arrived differently: they list, index, browse, and — because their
files carry the accession prefix that marks a file as ours — delete through the ordinary
genome-removal UI.

The files themselves are generated by ``scripts/build_demo_genome.py`` and
``scripts/build_grch38_slice.py``.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

from genome_identity import DEFAULT_PROVIDER, genome_manifest_filename


@dataclass(frozen=True)
class BundledGenome:
    """One genome that ships with the app rather than being downloaded.

    Everything a caller needs to install it, list it and browse it. It exists because
    there are two of these now and every one of the values below used to be a module
    constant — which worked exactly until there was a second genome.
    """

    genome_id: str
    source_dir_name: str
    species_key: str
    assembly: str
    assembly_name: str
    scientific_name: str
    common_name: str
    display_name: str
    # A URL scheme that is obviously not a download, but is non-empty — which is what
    # marks the files as ours to delete rather than as something the user brought in.
    # See ``main._is_download_managed_assembly``.
    url_scheme: str
    # source filename -> (path within the assembly directory, file type). The accession
    # prefix is what ``main._downloaded_assembly_files`` looks for, so it is not
    # decoration. A file type of "" is a sidecar: copied, but not a file in its own right.
    files: Dict[str, Tuple[str, str]]
    # Region -> (start, end) that is worth looking at, when that is narrower than the
    # region itself. The chromosome-1 slice is a real chromosome coordinate space with a
    # small window of real sequence in it, so without this the browser lets you pan out
    # into a hundred megabases of padding — which reads as the app being broken rather
    # than as the edge of a slice. Surfaced by /api/browse/regions and enforced by the
    # browser's own clampView; absent for everything else, which is unaffected.
    browsable_range: Dict[str, Tuple[int, int]] = field(default_factory=dict)
    blurb: str = ""
    provider: str = DEFAULT_PROVIDER
    # The annotation goes in a dataset release of its own rather than loose in the
    # assembly directory. Loose annotations are swept into the "legacy/unknown" bucket,
    # which the UI quite reasonably labels "Legacy local files" — true of a genome someone
    # copied in by hand years ago, and wrong for these. A real release also matches what a
    # download produces.
    release_source: str = "demo"
    release_date: str = "current"
    release_label: str = "Demo"

    @property
    def release_key(self) -> str:
        return f"{self.release_source}/{self.release_date}"

    @property
    def annotation_path(self) -> str:
        """Where the GFF3 lands inside the assembly directory."""
        for installed_path, file_type in self.files.values():
            if file_type == "gff3":
                return installed_path
        raise KeyError(f"{self.genome_id} bundles no annotation")


DEMO_GENOME_ID = "ensemblus_welcomus"
SLICE_GENOME_ID = "grch38_reg4"

DEMO_GENOME = BundledGenome(
    genome_id=DEMO_GENOME_ID,
    source_dir_name="demo_genome",
    species_key="ensemblus_welcomus",
    assembly="GCA_000000000.1",
    assembly_name="EnsWel1.0",
    scientific_name="Ensemblus welcomus",
    common_name="Demo genome",
    display_name="Ensemblus welcomus (demo)",
    url_scheme="demo://ensemblus-welcomus",
    blurb="Two contigs, six genes, and a sense of humour about its gene names.",
    files={
        "demo.fa": ("GCA_000000000.1.fa", "fasta"),
        "demo.fa.fai": ("GCA_000000000.1.fa.fai", ""),
        "demo.gff3": ("datasets/demo/current/GCA_000000000.1.gff3", "gff3"),
        "demo_assembly_report.txt": ("GCA_000000000.1_assembly_report.txt", "metadata"),
    },
)

# Deliberately *not* the real GRCh38 accession. Claiming GCA_000001405.29 would put this
# in the same directory as a genuinely downloaded human genome, and everything that
# resolves a genome by accession — the remote catalogue, the manifest reader, the
# retired-remote check — would then conflate half a megabase of chromosome 1 with the
# whole assembly.
SLICE_GENOME = BundledGenome(
    genome_id=SLICE_GENOME_ID,
    source_dir_name="grch38_reg4",
    species_key="homo_sapiens_demo_slice",
    assembly="GCA_000000000.2",
    assembly_name="GRCh38-REG4-slice",
    scientific_name="Homo sapiens (demo slice)",
    common_name="Human chr1 slice",
    display_name="Human chr1 slice (demo)",
    url_scheme="demo://grch38-reg4-slice",
    browsable_range={"1": (118_440_000, 120_120_000)},
    blurb="Half a megabase of real chromosome 1 around REG4, with its Ensembl annotation.",
    files={
        "grch38_reg4.fa.bgz": ("GCA_000000000.2.fa.bgz", "fasta"),
        "grch38_reg4.fa.bgz.fai": ("GCA_000000000.2.fa.bgz.fai", ""),
        "grch38_reg4.fa.bgz.gzi": ("GCA_000000000.2.fa.bgz.gzi", ""),
        "grch38_reg4.gff3.gz": ("datasets/demo/current/GCA_000000000.2.gff3.gz", "gff3"),
        "grch38_reg4_assembly_report.txt": ("GCA_000000000.2_assembly_report.txt", "metadata"),
    },
)

BUNDLED_GENOMES: Dict[str, BundledGenome] = {
    DEMO_GENOME.genome_id: DEMO_GENOME,
    SLICE_GENOME.genome_id: SLICE_GENOME,
}

BUNDLED_SPECIES_KEYS = frozenset(genome.species_key for genome in BUNDLED_GENOMES.values())


def bundled_genome(genome_id: Any = None) -> BundledGenome:
    """Look one up, defaulting to the demo genome so old callers keep working."""
    key = str(genome_id or "").strip() or DEMO_GENOME_ID
    genome = BUNDLED_GENOMES.get(key)
    if genome is None:
        raise ValueError(f"Unknown bundled genome: {key}")
    return genome


# Kept as names because the first tutorial, the download view and a good deal of
# main.py refer to the demo genome by them. They are the demo genome's fields.
DEMO_PROVIDER = DEMO_GENOME.provider
DEMO_SPECIES_KEY = DEMO_GENOME.species_key
DEMO_ASSEMBLY = DEMO_GENOME.assembly
DEMO_ASSEMBLY_NAME = DEMO_GENOME.assembly_name
DEMO_SCIENTIFIC_NAME = DEMO_GENOME.scientific_name
DEMO_COMMON_NAME = DEMO_GENOME.common_name
DEMO_DISPLAY_NAME = DEMO_GENOME.display_name
DEMO_URL_SCHEME = DEMO_GENOME.url_scheme
DEMO_RELEASE_SOURCE = DEMO_GENOME.release_source
DEMO_RELEASE_DATE = DEMO_GENOME.release_date
DEMO_RELEASE_KEY = DEMO_GENOME.release_key
DEMO_RELEASE_LABEL = DEMO_GENOME.release_label
DEMO_FILES = DEMO_GENOME.files


# A tutorial runs against its own scratch directory inside the output directory the user
# has already chosen, so nothing it does can land among their real genomes. The leading
# dot keeps it out of the way; it is created on start and removed on exit, and swept on
# launch in case the app was killed mid-tutorial.
TUTORIAL_WORKSPACE_DIR = ".ensembl_go_tutorial"


def tutorial_workspace(output_dir: str) -> Path:
    """The tutorial's scratch directory inside ``output_dir``."""
    root = str(output_dir or "").strip()
    if not root:
        raise ValueError("An output directory is needed before a tutorial can run.")
    return Path(root).expanduser().resolve() / TUTORIAL_WORKSPACE_DIR


def reset_tutorial_workspace(output_dir: str) -> Dict[str, Any]:
    """Remove the tutorial's scratch directory, if it is there.

    Deliberately narrow: it will only ever delete a directory named exactly
    ``TUTORIAL_WORKSPACE_DIR`` directly inside the given output directory, so a wrong or
    empty ``output_dir`` cannot turn this into a recursive delete of anything else.
    """
    workspace = tutorial_workspace(output_dir)
    if workspace.name != TUTORIAL_WORKSPACE_DIR:
        raise ValueError("Refusing to remove anything but the tutorial workspace.")
    if workspace.is_symlink():
        raise ValueError("The tutorial workspace may not be a symlink.")
    existed = workspace.is_dir()
    if existed:
        shutil.rmtree(workspace)
    return {"removed": existed, "workspace": str(workspace)}


def demo_source_dir(genome_id: Any = None) -> Path:
    """Where a bundled fixture lives.

    Same idiom as ``project_classifier.DEFAULT_PROJECT_ARTIFACT_PATH``, which already
    resolves correctly in the PyInstaller build — ``backend/data`` is bundled wholesale
    by ``electron/scripts/build-backend.js``.
    """
    return Path(__file__).resolve().parent / "data" / bundled_genome(genome_id).source_dir_name


def demo_assembly_dir(output_dir: str, genome_id: Any = None) -> Path:
    genome = bundled_genome(genome_id)
    return (
        Path(output_dir).expanduser().resolve()
        / "local_data"
        / genome.species_key
        / genome.assembly
    )


def demo_catalogue_entry(genome_id: Any = None) -> Dict[str, Any]:
    """A bundled genome shaped like a row from ``/api/remote/species``.

    The download view renders it with the same components as everything else, so a
    tutorial can teach the real UI rather than a mock of it.
    """
    genome = bundled_genome(genome_id)
    return {
        "key": genome.species_key,
        "scientific_name": genome.scientific_name,
        "common_name": genome.common_name,
        "display_name": genome.display_name,
        "display_name_reason": "demo",
        "provider": genome.provider,
        "is_demo": True,
        "demo_genome_id": genome.genome_id,
        "assemblies": [
            {
                "accession": genome.assembly,
                "gca": genome.assembly,
                "name": genome.assembly_name,
                "source_database": "demo",
                "is_demo": True,
                "equivalent_accessions": [],
            }
        ],
    }


def demo_files_present(asm_dir: Path, genome_id: Any = None) -> Dict[str, str]:
    """Which of a bundled genome's files are on disk, by type."""
    found: Dict[str, str] = {}
    for _source, (installed_path, file_type) in bundled_genome(genome_id).files.items():
        if not file_type:
            continue
        candidate = asm_dir / installed_path
        if candidate.is_file() and candidate.stat().st_size > 0:
            found[file_type] = str(candidate)
    return found


def demo_install_status(output_dir: str, genome_id: Any = None) -> Dict[str, Any]:
    """Whether a bundled genome is already installed under this output directory."""
    genome = bundled_genome(genome_id)
    asm_dir = demo_assembly_dir(output_dir, genome.genome_id) if output_dir else None
    files = demo_files_present(asm_dir, genome.genome_id) if asm_dir and asm_dir.is_dir() else {}
    # A FASTA and an annotation is what makes it usable; the rest is trimming.
    installed = bool(files.get("fasta") and files.get("gff3"))
    return {
        "installed": installed,
        "genome_id": genome.genome_id,
        "provider": genome.provider,
        "species_key": genome.species_key,
        "assembly": genome.assembly,
        "assembly_name": genome.assembly_name,
        "directory": str(asm_dir) if asm_dir else "",
        "files": files,
        "species": demo_catalogue_entry(genome.genome_id),
        "available": demo_source_dir(genome.genome_id).is_dir(),
    }


def demo_install_statuses(output_dir: str) -> list:
    """Every bundled genome's status, in registration order."""
    return [demo_install_status(output_dir, genome_id) for genome_id in BUNDLED_GENOMES]


def _manifest(now: str, asm_dir: Path, genome: BundledGenome) -> Dict[str, Any]:
    manifest: Dict[str, Any] = {
        # Version 2 is what marks a manifest as listing its individual files, which is
        # what the delete path reads.
        "manifest_version": 2,
        "provider": genome.provider,
        "source_database": "demo",
        "species_key": genome.species_key,
        "assembly": genome.assembly,
        "assembly_name": genome.assembly_name,
        "scientific_name": genome.scientific_name,
        "common_name": genome.common_name,
        "display_name": genome.display_name,
        "display_name_reason": "demo",
        "gca": genome.assembly,
        "equivalent_accessions": [],
        "is_demo": True,
        "demo_genome_id": genome.genome_id,
        "browsable_range": {k: list(v) for k, v in genome.browsable_range.items()},
        "updated_at": now,
        "assembly_files": {},
        "dataset_releases": {},
    }
    for _source, (installed_path, file_type) in genome.files.items():
        if not file_type:
            continue
        record = {
            "type": file_type,
            "filename": Path(installed_path).name,
            "path": str(asm_dir / installed_path),
            "url": f"{genome.url_scheme}/{Path(installed_path).name}",
            "downloaded_at": now,
        }
        # Mirrors main.ASSEMBLY_SCOPED_FILE_TYPES; a gff3 is dataset-scoped.
        if file_type in {"fasta", "metadata"}:
            manifest["assembly_files"][file_type] = record
        else:
            release = manifest["dataset_releases"].setdefault(
                genome.release_key,
                {
                    "key": genome.release_key,
                    "source": genome.release_source,
                    "date": genome.release_date,
                    "label": genome.release_label,
                    "files": {},
                    "created_at": now,
                },
            )
            release["files"][file_type] = record
    return manifest


def install_demo_genome(output_dir: str, genome_id: Any = None) -> Dict[str, Any]:
    """Copy a bundled genome into ``output_dir`` and record it like a download.

    Idempotent: installing twice just refreshes the files.
    """
    genome = bundled_genome(genome_id)
    if not str(output_dir or "").strip():
        raise ValueError("An output directory is needed before the demo genome can be installed.")

    source_dir = demo_source_dir(genome.genome_id)
    if not source_dir.is_dir():
        raise FileNotFoundError(f"The bundled genome {genome.genome_id} is missing from {source_dir}.")

    asm_dir = demo_assembly_dir(output_dir, genome.genome_id)
    asm_dir.mkdir(parents=True, exist_ok=True)

    copied = []
    for source_name, (installed_path, _file_type) in genome.files.items():
        source = source_dir / source_name
        if not source.is_file():
            raise FileNotFoundError(f"The bundled genome {genome.genome_id} is missing {source_name}.")
        destination = asm_dir / installed_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, destination)
        copied.append(installed_path)

    now = datetime.utcnow().isoformat() + "Z"
    manifest_path = asm_dir / genome_manifest_filename(genome.assembly)
    manifest_path.write_text(json.dumps(_manifest(now, asm_dir, genome), indent=2), encoding="utf-8")

    status = demo_install_status(output_dir, genome.genome_id)
    status["copied"] = copied
    status["manifest"] = str(manifest_path)
    return status


def demo_index_target(output_dir: str, genome_id: Any = None) -> Optional[tuple]:
    """(gff path, index path) for a bundled annotation, once installed.

    The index sits beside the annotation, in the release directory, which is where the
    scanner looks for it, and carries the accession-prefixed name the scanner treats as
    canonical — ``<assembly>.gff3.index.db``, whether or not the GFF3 itself is gzipped.
    """
    genome = bundled_genome(genome_id)
    asm_dir = demo_assembly_dir(output_dir, genome.genome_id)
    gff = asm_dir / genome.annotation_path
    if not gff.is_file():
        return None
    return str(gff), str(gff.parent / f"{genome.assembly}.gff3.index.db")


# ── The running tutorial's genomes, as far as the backend is concerned ───────────
#
# A tutorial never writes to the user's configuration — that is the whole point of the
# sandbox. But the genome browser is resolved *server-side*, from the configuration on
# disk: ``main._resolve_browse_genome_context`` looks the requested genome key up in
# ``active_species`` and rejects anything it cannot find. So a genome that exists only in
# the frontend's config override is, to the browser, not a genome at all — every request
# comes back 400 and the tracks stay blank.
#
# This is the missing half: an in-memory note of the genomes a running tutorial has
# activated. It lives for the life of the process, is never written anywhere, and is
# accepted only for a bundled genome inside a tutorial workspace — so it can add exactly
# the tutorials' own genomes to what the browser can resolve, and nothing else.
#
# The workspace path is remembered alongside them because the sandbox reaches further
# than the browser: notes are written through ``load_config()``, which reads the *real*
# configuration, so without knowing where the tutorial is running a note taken during one
# would land in the user's own notes file and outlive the tutorial. See
# ``main._notes_config``.

_tutorial_session: Dict[str, Dict[str, Any]] = {}
_tutorial_workspace_root: Optional[str] = None


def _is_inside_tutorial_workspace(path: Any) -> bool:
    text = str(path or "").strip()
    if not text:
        return False
    return TUTORIAL_WORKSPACE_DIR in Path(text).parts


def _workspace_root_of(path: Any) -> Optional[str]:
    """The tutorial workspace a file sits inside, if it sits inside one."""
    parts = Path(str(path)).parts
    if TUTORIAL_WORKSPACE_DIR not in parts:
        return None
    return str(Path(*parts[: parts.index(TUTORIAL_WORKSPACE_DIR) + 1]))


def set_tutorial_session_genome(record: Any) -> Dict[str, Any]:
    """Register a bundled genome as browsable for the life of this process.

    Validated rather than trusted: it must be one of the genomes this app bundles, and
    every file it names must sit inside a tutorial workspace. A record failing either
    test is refused, so this cannot be used to make some other genome resolvable behind
    the configuration's back.
    """
    global _tutorial_workspace_root
    if not isinstance(record, dict):
        raise ValueError("A genome record is required.")
    species_key = str(record.get("species_key") or "").strip()
    is_bundled = species_key in BUNDLED_SPECIES_KEYS
    generated_id = str(record.get("tutorial_dataset_id") or "").strip()
    if not is_bundled and not generated_id:
        raise ValueError("Only a bundled or validated generated tutorial genome may be registered.")
    files = record.get("files") or {}
    if not isinstance(files, dict) or not files:
        raise ValueError("The demo genome record names no files.")
    workspace = None
    for value in files.values():
        if isinstance(value, str) and value.strip():
            if not _is_inside_tutorial_workspace(value):
                raise ValueError("The demo genome must live inside the tutorial workspace.")
            workspace = workspace or _workspace_root_of(value)
    if not is_bundled:
        assembly = str(record.get("assembly") or "").strip()
        marker_candidates = [
            Path(value).resolve().parent / "tutorial_dataset.json"
            for value in files.values() if isinstance(value, str) and value.strip()
        ]
        marker_path = next((path for path in marker_candidates if path.is_file()), None)
        if marker_path is None:
            raise ValueError("The generated tutorial genome has no validation marker.")
        try:
            marker = json.loads(marker_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError("The generated tutorial genome marker is unreadable.") from exc
        if marker.get("tutorial_dataset_id") != generated_id or marker.get("species_key") != species_key or marker.get("assembly") != assembly:
            raise ValueError("The generated tutorial genome does not match its validation marker.")
    _tutorial_session[species_key] = dict(record)
    _tutorial_workspace_root = workspace or _tutorial_workspace_root
    return _tutorial_session[species_key]


def clear_tutorial_session_genome() -> None:
    global _tutorial_workspace_root
    _tutorial_session.clear()
    _tutorial_workspace_root = None


def tutorial_session_species() -> list:
    """The extra active genomes a running tutorial contributes, if any."""
    return [dict(record) for record in _tutorial_session.values()]


def tutorial_session_workspace() -> Optional[str]:
    """The workspace a tutorial is running in, while one is running.

    ``None`` the rest of the time, which is what callers use to tell "sandboxed" from
    "not" without having to reach into the frontend's configuration override.
    """
    return _tutorial_workspace_root if _tutorial_session else None
